# Generated by Django 2.1 on 2018-08-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmabook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cidade',
            new_name='address',
        ),
    ]
