# Generated by Django 2.1 on 2018-08-31 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmabook', '0003_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ṕublished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
