# Generated by Django 2.1 on 2018-08-31 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmabook', '0005_auto_20180831_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('value', models.FloatField()),
                ('note', models.TextField()),
                ('expires_at', models.DateTimeField(null=True, verbose_name='Expira em:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ṕublished_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmabook.Empregado')),
            ],
        ),
    ]
