# Generated by Django 2.1 on 2018-09-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmabook', '0007_endereco_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='author',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='address',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='author',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
    ]
