# Generated by Django 2.1 on 2018-09-03 21:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmabook', '0008_auto_20180902_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Aluno',
        ),
    ]
