# Generated by Django 2.1 on 2018-09-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmabook', '0010_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='devolution_date',
        ),
    ]
