# Generated by Django 2.1 on 2018-09-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmabook', '0011_auto_20180903_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='module',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='phone',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
